

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Banknote grade" AS ENUM (
    'G',
    'VG',
    'F',
    'VF',
    'XF',
    'AU',
    'UNC'
);


ALTER TYPE "public"."Banknote grade" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."banknotes" (
    "banknoteid" integer NOT NULL,
    "code" character varying(255) NOT NULL,
    "denomination" numeric(10,2) NOT NULL,
    "currencyid" integer,
    "year" integer,
    "width" numeric(10,2) NOT NULL,
    "height" numeric(10,2) NOT NULL,
    "material" character varying(100),
    "storageunitid" integer,
    "numistaid" integer,
    "grade" "public"."Banknote grade",
    "front_thumbnail" "text",
    "back_thumbnail" "text",
    "front_image" "text",
    "back_image" "text",
    "description" "text",
    "ownerid" "uuid" DEFAULT "auth"."uid"(),
    "added_on" "date" DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."banknotes" OWNER TO "postgres";


COMMENT ON COLUMN "public"."banknotes"."numistaid" IS 'ID of the item in Numista database';



COMMENT ON COLUMN "public"."banknotes"."front_image" IS 'Full resolution front image of the note';



COMMENT ON COLUMN "public"."banknotes"."added_on" IS 'Date when the banknote was added to collection';



ALTER TABLE "public"."banknotes" ALTER COLUMN "banknoteid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."banknotes_banknoteid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."countries" (
    "countryid" integer NOT NULL,
    "code" character varying(10) NOT NULL,
    "name" character varying(255) NOT NULL,
    "continentid" integer
);


ALTER TABLE "public"."countries" OWNER TO "postgres";


ALTER TABLE "public"."countries" ALTER COLUMN "countryid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."countries_countryid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."currencies" (
    "currencyid" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "code" character varying(10) NOT NULL,
    "symbol" character varying(10),
    "subunit" character varying(50),
    "numistaid" integer
);


ALTER TABLE "public"."currencies" OWNER TO "postgres";


COMMENT ON COLUMN "public"."currencies"."numistaid" IS 'Id of the currency in Numista database';



ALTER TABLE "public"."currencies" ALTER COLUMN "currencyid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."currencies_currencyid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."currencycountry" (
    "currencyid" integer NOT NULL,
    "countryid" integer NOT NULL,
    "iscurrent" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."currencycountry" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."storageunits" (
    "storageunitid" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."storageunits" OWNER TO "postgres";


ALTER TABLE "public"."storageunits" ALTER COLUMN "storageunitid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."storageunits_storageunitid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."banknotes"
    ADD CONSTRAINT "banknotes_banknoteid_key" UNIQUE ("banknoteid");



ALTER TABLE ONLY "public"."banknotes"
    ADD CONSTRAINT "banknotes_pkey" PRIMARY KEY ("banknoteid");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_code_key" UNIQUE ("code");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("countryid");



ALTER TABLE ONLY "public"."currencies"
    ADD CONSTRAINT "currencies_code_key" UNIQUE ("code");



ALTER TABLE ONLY "public"."currencies"
    ADD CONSTRAINT "currencies_numistaid_key" UNIQUE ("numistaid");



ALTER TABLE ONLY "public"."currencies"
    ADD CONSTRAINT "currencies_pkey" PRIMARY KEY ("currencyid");



ALTER TABLE ONLY "public"."currencycountry"
    ADD CONSTRAINT "currencycountry_pkey" PRIMARY KEY ("currencyid", "countryid");



ALTER TABLE ONLY "public"."storageunits"
    ADD CONSTRAINT "storageunits_pkey" PRIMARY KEY ("storageunitid");



CREATE INDEX "idx_countryid" ON "public"."currencycountry" USING "btree" ("countryid");



CREATE INDEX "idx_currencyid" ON "public"."currencycountry" USING "btree" ("currencyid");



CREATE INDEX "idx_storageunitid" ON "public"."banknotes" USING "btree" ("storageunitid");



ALTER TABLE ONLY "public"."banknotes"
    ADD CONSTRAINT "banknotes_currencyid_fkey" FOREIGN KEY ("currencyid") REFERENCES "public"."currencies"("currencyid") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."banknotes"
    ADD CONSTRAINT "banknotes_storageunitid_fkey" FOREIGN KEY ("storageunitid") REFERENCES "public"."storageunits"("storageunitid") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."currencycountry"
    ADD CONSTRAINT "currencycountry_countryid_fkey" FOREIGN KEY ("countryid") REFERENCES "public"."countries"("countryid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."currencycountry"
    ADD CONSTRAINT "currencycountry_currencyid_fkey" FOREIGN KEY ("currencyid") REFERENCES "public"."currencies"("currencyid") ON DELETE CASCADE;



CREATE POLICY "Allow all actions" ON "public"."countries" USING (true);



CREATE POLICY "Allow all actions" ON "public"."currencies" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all actions" ON "public"."currencycountry" USING (true);



CREATE POLICY "Private item acces" ON "public"."banknotes" USING (("ownerid" = "auth"."uid"()));



ALTER TABLE "public"."banknotes" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON TABLE "public"."banknotes" TO "anon";
GRANT ALL ON TABLE "public"."banknotes" TO "authenticated";
GRANT ALL ON TABLE "public"."banknotes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."banknotes_banknoteid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."banknotes_banknoteid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."banknotes_banknoteid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."countries" TO "anon";
GRANT ALL ON TABLE "public"."countries" TO "authenticated";
GRANT ALL ON TABLE "public"."countries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."countries_countryid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."countries_countryid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."countries_countryid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."currencies" TO "anon";
GRANT ALL ON TABLE "public"."currencies" TO "authenticated";
GRANT ALL ON TABLE "public"."currencies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."currencies_currencyid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."currencies_currencyid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."currencies_currencyid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."currencycountry" TO "anon";
GRANT ALL ON TABLE "public"."currencycountry" TO "authenticated";
GRANT ALL ON TABLE "public"."currencycountry" TO "service_role";



GRANT ALL ON TABLE "public"."storageunits" TO "anon";
GRANT ALL ON TABLE "public"."storageunits" TO "authenticated";
GRANT ALL ON TABLE "public"."storageunits" TO "service_role";



GRANT ALL ON SEQUENCE "public"."storageunits_storageunitid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."storageunits_storageunitid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."storageunits_storageunitid_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























drop extension if exists "pg_net";


